// Generated by scripts/rework-courses.mjs. Do not edit by hand.
export const MODULE_COUNTS: Record<string, number> = {
  "ai-marketing-and-aeo": 8,
  "applications-that-get-replies": 8,
  "becoming-an-ops-lead": 10,
  "bookkeeping-basics": 8,
  "complete-va-starter": 10,
  "customer-support": 8,
  "data-and-research": 8,
  "ecommerce-va": 8,
  "email-marketing": 8,
  "executive-assistant": 8,
  "general-va": 8,
  "graphic-design": 8,
  "pricing-and-negotiation": 9,
  "project-management": 8,
  "real-estate-va": 8,
  "sales-development": 8,
  "seo-specialist": 9,
  "social-media-manager": 8,
  "video-editing": 8,
  "web-and-no-code": 8,
  "writing-for-clients": 8
};
